export enum MessageResponseTypes {
    INITIAL_PLAYER = "initial_player",
    START_GAME = "start_game",
    NEW_PLAYER = "new_player",
    PLAYER_JOINED = "player_joined",
    PLAYER_LEFT = "player_left",
    PLAYER_READY = "player_ready",
    PLAYER_NOT_READY = "player_not_ready",
    PLAYER_BANKRUPT = "player_bankrupt",
    PLAYER_FINISHED_TURN = "player_finished_turn",
    PLAYER_ROLL_DICE = "player_roll_dice",
    PLAYER_BUY_PROPERTY = "player_buy_property",
    PLAYER_SELL_PROPERTY = "player_sell_property",
    PLAYER_MORTGAGE_PROPERTY = "player_mortgage_property",
    PLAYER_UNMORTGAGE_PROPERTY = "player_unmortgage_property",
    PLAYER_PAY_RENT = "player_pay_rent",
    PLAYER_MOVE_TO_JAIL = "player_move_to_jail",
    PLAYER_GET_OUT_OF_JAIL_CARD = "player_get_out_of_jail_card",
    AUCTION_START = "auction_start",
    AUCTION_BID_PLACED = "auction_bid_placed",
    AUCTION_ENDED = "auction_ended",
    PLAYER_RELEASED_FROM_JAIL = "player_released_from_jail",
    PLAYER_ROLLING_DICE = "player_rolling_dice",
}